### ISSUE TITLE
How to deal with SuiteScripts in a folder structure?

### ISSUE THREAD

**Issue by philipdenys** [ExploreConsulting/netsuite-sync#10]
I'm taking over a NetSuite project and the SuiteScript folder has different folders per SuiteScript type.

I saw the recommendation to use 
> as best practice to keep all suitescripts in a single folder if possible.

 But I was wondering if there was any work around for this?

**Comment by ShawnTalbert** [comment]
Netsuite-sync does have an `--folder` option where you can specify the folder id to send the file to. If you do `ns --help` it should show that option. Using this mechanism you can send any file to any folder.

However, I generally recommend using SDFCLI these days as it's officially supported by NetSuite. It does seem quite a bit slower at file uploads a bit more strict on structure but it does have the ability to upload an entire directory tree.

**Comment by philipdenys** [comment]
oh wow thanks, must have overlooked the folder option.
I'll take a look at the SDF CLI if I can find it ;)
