### ISSUE TITLE
Is this till working?

### ISSUE THREAD

**Issue by Esuk** [ExploreConsulting/netsuite-sync#6]
I'm running this on macos sierra and keeps getting the following error message when I try to upload my first testfile.

Macsuk5:netsuite mattias$ ns -u test2.txt 
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'writeResponse' of undefined
    at /usr/local/lib/node_modules/netsuite-sync/ns.js:69:48
    at /usr/local/lib/node_modules/netsuite-sync/lib/FileCabinet.js:174:20
    at Parser.<anonymous> (/usr/local/lib/node_modules/netsuite-sync/node_modules/xml2js/lib/xml2js.js:384:20)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/netsuite-sync/node_modules/xml2js/lib/xml2js.js:348:26)
    at emit (/usr/local/lib/node_modules/netsuite-sync/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/netsuite-sync/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/usr/local/lib/node_modules/netsuite-sync/node_modules/sax/lib/sax.js:861:5)
    at SAXParser.write (/usr/local/lib/node_modules/netsuite-sync/node_modules/sax/lib/sax.js:1294:29)

**Comment by ShawnTalbert** [comment]
@Esuk Check that your NetSuiteConfig is correct (account, username, password, folderid). We should improve the error messaging here.

I recommend setting up the config file with `ns -g`

**Comment by ShawnTalbert** [comment]
@smccleary it's likely due to the 2018.2 update if you were logging in with an _Administrator Role_ account. Switch to a less privileged role. 

What should happen is netsuite-sync should be enhanced to do TBA (token based authentication). Pull requests welcomed!

**Comment by smccleary** [comment]
ok will give that a try

**Comment by smccleary** [comment]
Actually it was at my IT Manager role. Tried all roles no luck. 

We cannot approve a PR for this as it was just a utility library to get over our hatred of Eclipse's CTRL+U. Thank you for everything nonetheless but we will go back to Eclipse

**Comment by ShawnTalbert** [comment]
For what it's worth, I don't use Eclipse at all. We use WebStorm.

**Comment by smccleary** [comment]
same here. I use eclipse just to upload lol. I code always in WS

**Comment by ShawnTalbert** [comment]
There is supposed to be a plugin for WebStorm releasing in the next couple weeks that will do what this utility does (and everything else the Eclipse plugin does).

What I'm curious to see if it allows me to enter credentials once rather than repeatedly. Entering credentials every time I upload would be quite frustrating IMHO.

**Comment by ShawnTalbert** [comment]
Interesting, maybe they are only enforcing changes on certain endpoints to
not completely break backward compatibility?

**Comment by smccleary** [comment]
Yeah we have several tickets in. Apparently anything and everything that uploads broke. Not just our co but some affiliates who have custom NS bundles as well. Gotta love NS!

**Comment by smccleary** [comment]
Just tried again and its working ok this morning. Ive ran it several times just to be sure. Eclipse CTRL+U is still busted though for us

**Comment by ShawnTalbert** [comment]
Good to know, thanks.
